#!/bin/bash
#SBATCH --job-name=resampling       # Job name
#SBATCH --output=resampling.%j.out      # Name of output file
#SBATCH --cpus-per-task=20      # CPU cores
#SBATCH --mem=16G       # Memory per node
#SBATCH --time=72:00:00     # Max run time (hh:mm:ss)
#SBATCH --partition=cores       # Run on scavenge queue 

echo "Job started"
echo "Running on node: $(hostname)"

module load Python/3.11.3-GCCcore-12.3.0
source /$HOME/bachelor2026/venv/bin/activate

# Run the script
cd "$SLURM_SUBMIT_DIR/scripts"

echo "Running resampling.py from: $(pwd)"
python resampling.py

echo "Job finished"
